name: Cloudflare Check

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  cloudflare-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          chromium-browser \
          chromium-chromedriver \
          xvfb \
          python3-tk \
          python3-dev \
          scrot
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install seleniumbase pyautogui
    
    - name: Set up display
      run: |
        export DISPLAY=:99
        sudo Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 3  # give xvfb time to start
    
    - name: Run test
      env:
        DISPLAY: :99
      run: python test_cloudflare.py